### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by vbajs**
So people can understand what this ;)
I might close this soon if no one saw it

### CODE REVIEW

**Comment by vbajs** [comment]
NO ONE MERGES IT EXCEPT @xX-Yoshi-Xx !!!!
If you merge it, i will revert it

**Comment by vbajs** [comment]
Notice me, senpai....
@xX-Yoshi-Xx

**Comment by vbajs** [comment]
This pull request has been about 4 months old so I might close it and abandon it

**Comment by r-matlock** [comment]
@vbajs we don't need this so I'll close it.

**Pull request closed without merging**
